include: package:flutter_lints/flutter.yaml

# Options are error, warning, info
# https://dart.dev/guides/language/analysis-options#customizing-analysis-rules
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
  plugins:
    - dart_code_metrics
  errors:
    always_declare_return_types: error
    always_specify_types: error
    always_use_package_imports: error
    annotate_overrides: error
    avoid_annotating_with_dynamic: error
    avoid_bool_literals_in_conditional_expressions: error
    avoid_print: error
    camel_case_extensions: error
    camel_case_types: error
    constant_identifier_names: error
    file_names: error
    invalid_annotation_target: ignore
    invalid_uri: error
    library_names: error
    lines_longer_than_80_chars: error
    missing_required_param: error
    no_runtimeType_toString: error
    non_constant_identifier_names: error
    noop_primitive_operations: error
    prefer_asserts_in_initializer_lists: error
    prefer_asserts_with_message: error
    prefer_contains: error
    prefer_expression_function_bodies: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_null_aware_operators: error
    prefer_single_quotes: error
    use_key_in_widget_constructors: error

#flutter pub run dart_code_metrics:metrics analyze lib
dart_code_metrics:
  anti-patterns:
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 10
    maximum-nesting-level: 5
    number-of-parameters: 4
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-returning-widgets
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - avoid-nested-conditional-expressions:
        acceptable-level: 2